// <auto-generated />
namespace CookBook.Domain.EF
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Changedcharactercincuisine : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedcharactercincuisine));
        
        string IMigrationMetadata.Id
        {
            get { return "201808311207383_Changed character c in cuisine"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
